[licenses]
allow = ["MIT", "Apache-2.0"]
copyleft = "deny"
confidence-threshold = 1.0

exceptions = [
    { allow = ["ISC"], name = "inotify-sys", version = "*" },
    { allow = ["ISC"], name = "inotify", version = "*" },
    { allow = ["CC0-1.0"], name = "notify", version = "*" },
    { allow = ["BSD-3-Clause"], name = "fuchsia-zircon", version = "*" },
    { allow = ["BSD-3-Clause"], name = "fuchsia-zircon-sys", version = "*" },
    { allow = ["BSD-3-Clause"], name = "instant", version = "*" },
    { allow = ["CC0-1.0"], name = "dunce", version = "*" },
]

[bans]
multiple-versions = "deny"
wildcards = "deny"

skip = [
    { name = "mio", version = "0.6.23" }, # upgrade notify
    { name = "miow", version = "0.2.2" }, # upgrade notify
    { name = "cfg-if", version = "0.1.10" },
    { name = "winapi", version = "0.2.8" }, # upgrade notify
    { name = "redox_syscall", version = "0.1.57" }, # old version in notify
]

[sources]
unknown-git = "deny"
